version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "TemplateApi"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-01a8fe0c15ba81bff", "subnet-0cefdc8f90898369b"]
              SecurityGroups: ["sg-08d9c4d53246f8fa3"]
              AssignPublicIp: "ENABLED"